services:
  eureka-service:
    env_file: ".env"
    environment:
      SERVICE_REGISTRY_IP: eureka-service
    networks:
      - net
    ports:
      - "${PORT_SERVICE_REGISTRY}:8761"

  gateway:
    env_file: ".env"
    environment:
      SERVICE_REGISTRY_IP: eureka-service
    networks:
      - net
    ports:
      - "${GATEWAY_PORT}:8080"

  profile-mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${PROFILE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${PROFILE_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PROFILE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROFILE_DB_NAME}
    networks:
      - net
    ports:
      - "${PROFILE_DB_PORT_EXTERNAL}:3306"

  posts-mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${POSTS_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${POSTS_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${POSTS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${POSTS_DB_NAME}
    networks:
      - net
    ports:
      - "${POSTS_DB_PORT_EXTERNAL}:3306"

  auth-mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${AUTH_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
    networks:
      - net
    ports:
      - "${AUTH_DB_PORT_EXTERNAL}:3306"

  notification-mysql:
    image: mysql:9.1
    environment:
      MYSQL_USER: ${NOTIFICATION_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${NOTIFICATION_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${NOTIFICATION_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NOTIFICATION_DB_NAME}
    networks:
      - net
    ports:
      - "${NOTIFICATION_DB_PORT_EXTERNAL}:3306"


  profile_microservice:
    depends_on:
      - profile-mysql
      - eureka-service
      - gateway
    env_file: ".env"
    environment:
      PROFILE_DB_IP: profile-mysql
      SERVICE_REGISTRY_IP: eureka-service
    networks:
      - net
    ports:
      - "${PROFILE_MICROSERVICE_PORT}:8083"


  auth_service:
    env_file: ".env"
    environment:
      AUTH_DB_IP: auth-mysql
      SERVICE_REGISTRY_IP: eureka-service
    depends_on:
      - auth-mysql
      - eureka-service
      - gateway
    networks:
      - net
    ports:
      - "${AUTH_MICROSERVICE_PORT}:8082"

  notification_service:
    env_file: ".env"
    environment:
      NOTIFICATION_DB_IP: notification-mysql
      SERVICE_REGISTRY_IP: eureka-service
    depends_on:
      - notification-mysql
      - eureka-service
      - gateway
    networks:
      - net
    ports:
      - "${NOTIFICATION_MICROSERVICE_PORT}:8085"


  posts_microservice:
    env_file: ".env"
    environment:
      POSTS_DB_IP: posts-mysql
      SERVICE_REGISTRY_IP: eureka-service
    depends_on:
      - posts-mysql
      - eureka-service
      - gateway
    networks:
      - net
    ports:
      - "${POSTS_MICROSERVICE_PORT}:8084"

networks:
  net: