services:
  eureka-service:
    build:
      context: ./Microservices
      dockerfile: service-registry/Dockerfile

  gateway:
    build:
      context: ./Microservices
      dockerfile: api-gateway/Dockerfile

  profile_mysql:
    volumes:
      - ./dev/database/profile:/var/lib/mysql

  posts_mysql:
    volumes:
      - ./dev/database/posts:/var/lib/mysql

  auth_mysql:
    volumes:
      - ./dev/database/auth:/var/lib/mysql

  notification_mysql:
    volumes:
      - ./dev/database/notification:/var/lib/mysql

  profile_microservice:
    build:
      context: ./Microservices
      dockerfile: profile/Dockerfile

  auth_service:
    build:
      context: ./Microservices
      dockerfile: identity-microservice/Dockerfile

  notification_service:
    build:
      context: ./Microservices
      dockerfile: notification-service/Dockerfile

  posts_microservice:
    build:
      context: ./Microservices
      dockerfile: posts/Dockerfile

