services:
  mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    container_name: dev_db
    environment:
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${MYSQLDB_NAME}
    networks:
      - net
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - ./dev/database:/var/lib/mysql

networks:
  net:
    driver: bridge