services:
  mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    container_name: dev_db
    environment:
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${MYSQLDB_NAME}
    networks:
      - net
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - ./dev/database:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  posts-service:
    image: your-repo/posts-service:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

  profile-service:
    image: your-repo/profile-service:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

  notification-service:
    image: your-repo/notification-service:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  net:
    driver: bridge