services:
  mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    container_name: dev_db
    environment:
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${MYSQLDB_NAME}
    networks:
      - net
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - ./dev/database:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:3.9.3
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_PORT}:2181"

  kafka:
    image: confluentinc/cp-kafka:3.9.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT}:9092"

networks:
  net:
    driver: bridge