services:
  profile_mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${PROFILE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${PROFILE_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PROFILE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROFILE_DB_NAME}
    networks:
      - net
    ports:
      - "${PROFILE_DB_PORT}:3306"
    volumes:
      - ./dev/database/profile:/var/lib/mysql

  mysql_auth:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
#      MYSQL_USER: ${AUTH_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
    networks:
      - net
    ports:
      - "${AUTH_DOCKER_DB_PORT}:${AUTH_DOCKER_DB_PORT}"
    volumes:
      - ./dev/database/auth:/var/lib/mysql

  eureka-service:
    build:
      context: ./Microservices/service-registry
      dockerfile: Dockerfile
    environment:
      PORT_SERVICE_REGISTRY: ${PORT_SERVICE_REGISTRY}
      SERVICE_REGISTRY_IP: eureka-service
    networks:
      - net
    ports:
      - "${PORT_SERVICE_REGISTRY}:${PORT_SERVICE_REGISTRY}"

  gateway:
    build:
      context: ./Microservices/api-gateway
      dockerfile: Dockerfile
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      SERVICE_REGISTRY_IP: eureka-service
      PORT_SERVICE_REGISTRY: ${PORT_SERVICE_REGISTRY}
    networks:
      - net
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

  auth_service:
    build:
      context: ./Microservices/IdentityMicroservice
      dockerfile: Dockerfile
    environment:
      AUTH_MICROSERVICE_PORT: ${AUTH_MICROSERVICE_PORT}
      AUTH_MYSQL_USERNAME: ${AUTH_MYSQL_USERNAME}
      AUTH_MYSQL_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      AUTH_MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      AUTH_DB_IP: mysql_auth
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_DOCKER_DB_PORT: ${AUTH_DOCKER_DB_PORT}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SERVICE_REGISTRY_IP: eureka-service
      PORT_SERVICE_REGISTRY: ${PORT_SERVICE_REGISTRY}
    depends_on:
      - mysql_auth
    networks:
      - net
    ports:
      - "${AUTH_MICROSERVICE_PORT}:${AUTH_MICROSERVICE_PORT}"



networks:
  net:
    driver: bridge