services:
  profile_mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${PROFILE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${PROFILE_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PROFILE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROFILE_DB_NAME}
    networks:
      - net
    ports:
      - "${PROFILE_DB_PORT}:3306"
    volumes:
      - ./dev/database/profile:/var/lib/mysql

  mysql_auth:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
#      MYSQL_USER: ${AUTH_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
    networks:
      - net
    ports:
      - "${AUTH_DOCKER_DB_PORT}:3306"
    volumes:
      - ./dev/database/auth:/var/lib/mysql

  auth_service:
    build:
      context: ./Microservices/IdentityMicroservice
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_auth:3306/${AUTH_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${AUTH_MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_MYSQL_PASSWORD}
    depends_on:
      - mysql_auth
    networks:
      - net
    ports:
      - "8080:${AUTH_MICROSERVICE_PORT}"

networks:
  net:
    driver: bridge

#  mysql_service_2:
#    # Always specify what version, "latest" causes issues later on
#    image: mysql:9.1
#    environment:
#      MYSQL_USER: ${MYSQLDB_USER}
#      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD_ROOT}
#      MYSQL_DATABASE: ${MYSQLDB_NAME}
#    networks:
#      - net
#    ports:
#      - "${MYSQLDB_PORT}:3306"
#    volumes:
#      - ./dev/database/service_2:/var/lib/mysql

#networks:
#  net:
#    driver: bridge