services:
  eureka-service:
    build:
      context: ./Microservices/service-registry
      dockerfile: Dockerfile
    env_file: ".env"
    environment:
      SERVICE_REGISTRY_IP: eureka-service
    networks:
      - net
    ports:
      - "${PORT_SERVICE_REGISTRY}:8761"

  gateway:
    build:
      context: ./Microservices/api-gateway
      dockerfile: Dockerfile
    env_file: ".env"
    environment:
      SERVICE_REGISTRY_IP: eureka-service
    networks:
      - net
    ports:
      - "${GATEWAY_PORT}:8080"

  profile_mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${PROFILE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${PROFILE_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PROFILE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROFILE_DB_NAME}
    networks:
      - net
    ports:
      - "${PROFILE_DB_PORT_EXTERNAL}:3306"
    volumes:
      - ./dev/database/profile:/var/lib/mysql

  posts_mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${POSTS_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${POSTS_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${POSTS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${POSTS_DB_NAME}
    networks:
      - net
    ports:
      - "${POSTS_DB_PORT_EXTERNAL}:3306"
    volumes:
      - ./dev/database/posts:/var/lib/mysql

  auth_mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${AUTH_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
    networks:
      - net
    ports:
      - "${AUTH_DOCKER_DB_PORT}:3306"
    volumes:
      - ./dev/database/auth:/var/lib/mysql

  profile_microservice:
    container_name: profile_microservice
    depends_on:
      - profile_mysql
      - eureka-service
      - gateway
    # Path to teh root dir of teh microservice (where teh Dockerfile is)
    build:
      context: ./Microservices
      dockerfile: Profile/Dockerfile
      args:

        # name of teh folder in Microservices
        SERVICE_PATH: "Profile"
    # pass in the env file to be used
    env_file: ".env"
    environment:
      PROFILE_DB_IP: profile_mysql
      SERVICE_REGISTRY_IP: eureka-service
    ports:
      # ideally it would be mapped to a more static internal port
      # - "${PROFILE_MICROSERVICE_PORT}:8080"
      - "${PROFILE_MICROSERVICE_PORT}:${PROFILE_MICROSERVICE_PORT}"
    networks:
      - net


  auth_service:
    build:
      context: ./Microservices/IdentityMicroservice
      dockerfile: Dockerfile
    env_file: ".env"
    environment:
      AUTH_DB_IP: auth_mysql
      SERVICE_REGISTRY_IP: eureka-service
    depends_on:
      - auth_mysql
      - eureka-service
      - gateway
    networks:
      - net
    ports:
      - "${AUTH_MICROSERVICE_PORT}:8082"

  posts_microservice:
    container_name: posts_microservice
    build:
      context: ./Microservices/Posts
      dockerfile: Dockerfile
    env_file: ".env"
    environment:
      POSTS_DB_IP: posts_mysql
      SERVICE_REGISTRY_IP: eureka-service
    depends_on:
      - posts_mysql
      - eureka-service
      - gateway
    ports:
      - "${POSTS_MICROSERVICE_PORT}:${POSTS_MICROSERVICE_PORT}"
    networks:
      - net

  # Kafka Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - net
    ports:
      - "2181:2181"
    restart: on-failure


  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - net
    ports:
      - "9092:9092"
    restart: on-failure

  kafka-2: #Second Broker
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    networks:
      - net
    depends_on:
      - zookeeper
    restart: on-failure

  kafka-3: #Third Broker
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
    networks:
      - net
    depends_on:
      - zookeeper
    restart: on-failure
networks:
  net:
    driver: bridge
