services:
  profile_mysql:
    # Always specify what version, "latest" causes issues later on
    image: mysql:9.1
    environment:
      MYSQL_USER: ${PROFILE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${PROFILE_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PROFILE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROFILE_DB_NAME}
    networks:
      - net
    ports:
      - "${PROFILE_DB_PORT_EXTERNAL}:3306"
    volumes:
      - ./dev/database/profile:/var/lib/mysql

  profile_microservice:
    container_name: profile_microservice
    depends_on:
      - profile_mysql
    # Path to teh root dir of teh microservice (where teh Dockerfile is)
    build:
      context: ./Microservices
      dockerfile: Profile/Dockerfile
      args:
        # name of teh folder in Microservices
        SERVICE_PATH: "Profile"
    # pass in the env file to be used
    env_file: ".env"
    ports:
      # ideally it would be mapped to a more static internal port
      # - "${PROFILE_MICROSERVICE_PORT}:8080"
      - "${PROFILE_MICROSERVICE_PORT}:${PROFILE_MICROSERVICE_PORT}"
    networks:
      - net

networks:
  net:
    driver: bridge