name: Build
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        service:
          - "api-gateway"
          - "identity-microservice"
          - "notification-service"
          - "posts"
          - "profile"
          - "service-registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build ${{ matrix.service }}
        run:  |
          cd Microservices/${{ matrix.service }}
          mvn clean package -DskipTests=true
      - uses: azure/docker-login@v1
        with:
          login-server: cs4337.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd Microservices/${{ matrix.service }}
          docker build . -t cs4337.azurecr.io/${{ matrix.service }}:${{ github.sha }} -t cs4337.azurecr.io/${{ matrix.service }}:latest
          docker push cs4337.azurecr.io/${{ matrix.service }}:${{ github.sha }}