name: Deploy
on:
  workflow_run:
    workflows: [Build]
    branches:
      - "main"
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /cs4337
            git pull origin main
            docker compose -f base.docker-compose.yml -f prod.docker-compose.yml pull
            docker compose -f base.docker-compose.yml -f prod.docker-compose.yml down
            # rm -rf dev
            docker compose -f base.docker-compose.yml -f prod.docker-compose.yml up -d
