name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main   

jobs: 
  lint:
    strategy:
      matrix:
        service:
          - "api-gateway"
          - "IdentityMicroservice"
          - "notification-service"
          - "Posts"
          - "Profile"
          - "service-registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build ${{ matrix.service }}
        run: cd Microservices/${{ matrix.service }} && mvn checkstyle:check
      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
